[package]
name = "swagger"
version = "0.1.0"
authors = ["awygle <awygle@gmail.com>"]

[dependencies]
regex = "*"
lazy_static = "*"
mime = "*"
url = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
url_serde = "*"